name: in_app_review_platform_interface
description: A common platform interface for the in_app_review plugin.
# NOTE: We strongly prefer non-breaking changes, even at the expense of a
# less-clean API. See https://flutter.dev/go/platform-interface-breaking-changes
version: 1.0.3
homepage: https://github.com/britannio/in_app_review/tree/master/in_app_review_platform_interface

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.17.0 <2.0.0"

dependencies:
  flutter:
    sdk: flutter

  url_launcher: ^5.7.8
  package_info: '>=0.4.3 <2.0.0'
  plugin_platform_interface: ^1.0.3

  
dev_dependencies:
  flutter_test:
    sdk: flutter

  mockito: ^4.1.3
  