name: tests
env:
  FLUTTER_VERSION: "beta"
on:
  - push
  - pull_request
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: "12.x"
      - uses: britannio/action-install-flutter@v0.4
        with:
          version: $FLUTTER_VERSION
      - name: Get dependencies
        run: flutter pub get
        working-directory: ./in_app_review
      - name: Static Analysis
        run: flutter analyze --no-pub
        working-directory: ./in_app_review
      - name: Run Tests
        run: flutter test --no-pub
        working-directory: ./in_app_review
  platform_interface_tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: "12.x"
      - uses: britannio/action-install-flutter@v0.4
        with:
          version: $FLUTTER_VERSION
      - name: Get dependencies
        run: flutter pub get
        working-directory: ./in_app_review_platform_interface
      - name: Static Analysis
        run: flutter analyze --no-pub
        working-directory: ./in_app_review_platform_interface
      - name: Run Tests
        run: flutter test --no-pub
        working-directory: ./in_app_review_platform_interface
