name: tests
  
env:
  FLUTTER_VERSION: "2.10.0"
  
on:
  push:
  pull_request:
  
jobs:
  tests:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./in_app_review
    steps:
      - uses: actions/checkout@v2
      - uses: britannio/action-install-flutter@v1
        with:
          version: $FLUTTER_VERSION
      - name: Get dependencies
        run: flutter pub get
      - name: Static Analysis
        run: flutter analyze --no-pub
      - name: Run Tests
        run: flutter test --no-pub
          
  platform_interface_tests:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./in_app_review_platform_interface
    steps:
      - uses: actions/checkout@v2
      - uses: britannio/action-install-flutter@v1
        with:
          version: $FLUTTER_VERSION
      - name: Get dependencies
        run: flutter pub get
      - name: Static Analysis
        run: flutter analyze --no-pub
      - name: Run Tests
        run: flutter test --no-pub
